Updated Codebase and License
chrisseroka/ps-menu pull request #1
Opened 2018-03-30 21:57 UTC by sheldonhull

Hopefully these changes would be good with you. I really enjoyed using this module for a project and thought it could use a few tweaks and noticed a missing license in it. Put it MIT like dbatools and other projects are using and hopefully it would be cool with you. 
- Updated code from the latest changes in psgallery
- Included updated license agreement as no license provided and normally projects created now include them for proper reuse
- error handling put on if menu items null as this resolved issues with invalid index being found. I have option strict on so it might be catching the error that in non-strict mode would be allowable

2018-04-03 19:42 UTC, chrisseroka requested changes

2018-04-03 19:42 UTC, chrisseroka commented on ps-menu.psm1
> +	# ensure preferences passed down to continue into function
I think this comment does not bring much value, please remove

2018-04-03 19:42 UTC, chrisseroka commented on ps-menu.psm1
> +    for ($i = 0; $i -le $l; $i++)
I see a bug here, there should be: `$i -lt $l` instead (lower than vs lower than or equal)

2018-04-03 19:42 UTC, chrisseroka commented on ps-menu.psm1
> +        if(@($menuitems).count -gt 0)
And then we do not need this line (because of `$i -lt $l`)

2018-04-03 19:42 UTC, chrisseroka commented on ps-menu.psm1
> +        #if ($menuItems[$i] -ne $null)
leftover

2018-04-03 19:42 UTC, chrisseroka commented on ps-menu.psm1
> +            #write-verbose ($menuItems | format-table | out-string) -verbose
leftover

2018-04-03 19:42 UTC, chrisseroka commented on ps-menu.psm1
> +            #write-verbose "`$i: $i" -Verbose
leftover (commented code)

2018-04-03 19:42 UTC, chrisseroka commented on ps-menu.psm1
> +            if ($i -le (@($menuItems).count))
It's always true because of loop condition (with fix)

2018-04-04 23:35 UTC, sheldonhull commented
Thanks for the response, I'll be more than glad to fix. I just found an invalid array index that showed up after i sent this over. Can I will take your input and just do a new pull request with those fixes as well. cheers!

2018-04-04 23:35 UTC, closed without merging